### ISSUE TITLE
Typo in base_weatherentity.html

### ISSUE THREAD

**Issue by justme151** [vche/appdaemon_weatherentity#11]
Hi
thanks for your awesome work!

Your widget works like a charm but i just want to let you know that in line 152 in base_weatherentity.html the `class="vertical-detaili` has an extra 'i' at the end that leads to a slightly missalignment of the third weather forecast div because the padding of the vertical-detail css class is not applied.

https://github.com/vche/appdaemon_weatherentity/blob/1748dd943e1c9e4d626aaddb7b17e0ed04511377/base_weatherentity/base_weatherentity.html#L152

**Comment by vche** [comment]
oh, thanks ! 
Just pushed a commit to fix this, feel free to reopen if it doesn't fix it.
