### ISSUE TITLE
error in the weather forecast forecast is not displayed, only the immediate one is seen, the following days are not seen

### ISSUE THREAD

**Issue by juanjovi** [vche/appdaemon_weatherentity#15]
widget_type: weatherentity
has stopped working, show_forecast: is not displayed and stops the following
![forecast](https://github.com/vche/appdaemon_weatherentity/assets/48255832/0b06a7e7-cd79-43c2-a4b7-7f5e1dfacc84)

sorry for my bad English

**Comment by juanjovi** [comment]
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.weather_data.sensor
Fuente: custom_components/weather_data/sensor.py:186
integración: weather_data
Ocurrió por primera vez: 12:56:27 (13 ocurrencias)
Último inicio de sesión: 16:36:40

Retrying in 20 minutes: https://api.met.no/weatherapi/locationforecast/2.0/classic?lat=40.9754&lon=-5.6586&altitude=800 returned 403
Retrying in 16 minutes: https://api.met.no/weatherapi/locationforecast/2.0/classic?lat=40.9754&lon=-5.6586&altitude=800 returned 403
Retrying in 19 minutes: https://api.met.no/weatherapi/locationforecast/2.0/classic?lat=40.9754&lon=-5.6586&altitude=800 returned 403
Retrying in 20 minutes:
Retrying in 18 minutes: https://api.met.no/weatherapi/locationforecast/2.0/classic?lat=40.9754&lon=-5.6586&altitude=800 returned 403

**Comment by vche** [comment]
Duplicate with #14 , see investigaiton there
