### ISSUE TITLE
 missing partially cloudy condition forecast icon

### ISSUE THREAD

**Issue by SoulStarver** [vche/appdaemon_weatherentity#4]
![partlycloudy](https://user-images.githubusercontent.com/93984205/140916263-584f1b01-f768-424c-8dda-b1000bfe6ba2.png)

**Comment by fkolacek** [comment]
Most probably problem due to change in the name of the MDI icon as mentioned in https://github.com/home-assistant/core/issues/26257

`weather-partlycloudy` became `weather-partly-cloudy`

**Comment by fkolacek** [comment]
Very ugly workaround for now is to add following to the base_weatherentity.js line 213:

```
if(forecast.condition == "partlycloudy"){ forecast.condition = "partly-cloudy"; }
```

**Comment by vche** [comment]
thanks for reporting this and proposing a fix. I should be able to take a look by end of next week ! If you want to push a merge request in the meantime you're welcome to do so.

**Comment by vche** [comment]
Added mapping to mdi icons based on @fkolacek fix proposal (thanks).

<img width="378" alt="issue5" src="https://user-images.githubusercontent.com/3978524/152687683-d14c6fb2-0673-4aef-9e7f-201d2a71c98b.png">
)

Let me know if that fixes your issue. I will close the issue next week if no comments
