### ISSUE TITLE
ClimaCell Implementation Rain Amount/Probablility not rounded and no units

### ISSUE THREAD

**Issue by PFHUTCHINS** [vche/appdaemon_weatherentity#6]
The weatherenitity works well with ClimaCell except for the Precipitation Amount. This value is not rounded and can sometimes contain 10 digits to the right of the decimal, which causes the cells to wrap around beneath the row below it. I've attached a screenshot of an example. Can you help?

-
![ClimaCell Implementation](https://user-images.githubusercontent.com/47981385/152437131-2386f63e-0fdc-4dc4-93ea-08f798be5532.jpg)

**Comment by vche** [comment]
Rounded to 2 digits, as you can see before and after.
<img width="379" alt=" before" src="https://user-images.githubusercontent.com/3978524/152687993-3e41f476-d1a6-41e1-becb-c8a5a25d8e01.png">
<img width="376" alt="after" src="https://user-images.githubusercontent.com/3978524/152687996-5f3be06c-9411-479d-a7fb-9560c9c62349.png">



Let me know if that fix your issue. I will close the issue next week if no comments.

**Comment by PFHUTCHINS** [comment]
Thank you for the quick response. This fixed the rounding issue, but what are the units of measure? Can you add units? 

![image](https://user-images.githubusercontent.com/47981385/152822478-b13917f7-9286-4e9e-9b1a-4e14e0968dc9.png)

**Comment by vche** [comment]
Hey ! I forgot to add the units indeed.

Units are [mm or inches](https://developers.home-assistant.io/docs/core/entity/weather/#forecast) depending on your config

I'll add a config to set it in a bit

**Comment by vche** [comment]
I also noticed that precipitation probability is now implemented, so i'll add the option to choose between % or mm/in

**Comment by vche** [comment]
the last commits should fix this

**Comment by PFHUTCHINS** [comment]
Looks fantastic! Thanks!

![image](https://user-images.githubusercontent.com/47981385/152896146-4d0055f4-56f1-4c61-819a-ed31ce678d5a.png)
