### ISSUE TITLE
icons not displayed

### ISSUE THREAD

**Issue by mauriziozito01** [vche/appdaemon_weatherentity#8]
![image](https://user-images.githubusercontent.com/75208171/167288869-6086fd1a-8508-4315-8c17-b5f11387f24f.png)

Can you help me understand how I can fix the problem?
Some icons are not displayed

thanks

Maurizio

**Comment by vche** [comment]
Hi, my best guess would be that the open weather api has changed and handle new/updated names for current conditions, leading to know icon found.

I will try to find time to check the open weather api and figure this out as soon as i can

**Comment by vche** [comment]
Hi, I have checked the latest [possible weather condition from homeassistant](https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/__init__.py#L51-L65) and implemented those [without exisiting icons](https://pictogrammers.github.io/@mdi/font/6.9.96/).

This should now cover all condititions.
