### ISSUE TITLE
Cosmetc arguments

### ISSUE THREAD

**Issue by Raphael99-99** [vche/appdaemon_weatherentity#9]
![weatherentity](https://user-images.githubusercontent.com/46441468/178899939-2e6942da-4962-4e55-a585-3f5b4bb1fdfe.png)

Please can you tell me how to color white the today and next days forecast? Thanks in advance and thank you for this wonderful widget

**Comment by Raphael99-99** [comment]
solved. Thanks

**Comment by vche** [comment]
Hi, sorry i couldn't reply earlier, I'm glad to hear you were able to fix this. All styles are in the css as you probablt figured out, but let me know if you need support. I'll leave this issue open for a bit longer in case you do.

**Comment by Raphael99-99** [comment]
Thank you very much

**Comment by Raphael99-99** [comment]
Thank you Vivien. All went fine
Regards
Il 24 set 2022, 15:17 +0200, Vivien Chene ***@***.***>, ha scritto:
